"""fix_fk

Revision ID: 29745f4f9deb
Revises: 5429a9e15d20
Create Date: 2025-03-02 22:15:20.653381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29745f4f9deb'
down_revision = '5429a9e15d20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_feedbacks_visit_id_clients', 'feedbacks', type_='foreignkey')
    op.create_foreign_key(op.f('fk_feedbacks_visit_id_visitors'), 'feedbacks', 'visitors', ['visit_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_feedbacks_visit_id_visitors'), 'feedbacks', type_='foreignkey')
    op.create_foreign_key('fk_feedbacks_visit_id_clients', 'feedbacks', 'clients', ['visit_id'], ['id'])
    # ### end Alembic commands ###