"""delete_unused_var

Revision ID: 78e5a55e2ba0
Revises: e20167a2d69d
Create Date: 2025-03-03 00:05:30.866791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78e5a55e2ba0'
down_revision = 'e20167a2d69d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_feedbacks_client_id_clients', 'feedbacks', type_='foreignkey')
    op.drop_column('feedbacks', 'client_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedbacks', sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('fk_feedbacks_client_id_clients', 'feedbacks', 'clients', ['client_id'], ['id'])
    # ### end Alembic commands ###