"""add application global settings

Revision ID: 7f1112ded3c9
Revises: 36761415de63
Create Date: 2025-03-02 21:03:38.018225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f1112ded3c9'
down_revision = 'f60d2908c443'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_global_settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_application_global_settings'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('application_global_settings')
    # ### end Alembic commands ###