"""feedback_created_at

Revision ID: 8760cce3f58d
Revises: 78e5a55e2ba0
Create Date: 2025-03-03 15:42:11.417225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8760cce3f58d'
down_revision = '78e5a55e2ba0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedbacks', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedbacks', 'created_at')
    # ### end Alembic commands ###