"""add_place_cascade

Revision ID: e20167a2d69d
Revises: 29745f4f9deb
Create Date: 2025-03-02 23:15:21.799117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e20167a2d69d'
down_revision = '29745f4f9deb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###