"""fix_cascade_del

Revision ID: f60d2908c443
Revises: 36761415de63
Create Date: 2025-03-02 21:01:51.361668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f60d2908c443'
down_revision = '36761415de63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###